language: python

python:
  - "3.6-dev"

#install dependences
install:
  - pip install -r requirements.txt
  - pip install coverage

#Run tests
script:
  - coverage run -m pytest app/tests/test_views.py
  - coverage run -m pytest app/tests/test_models.py

after_success:
  - coveralls
