language: python

python:
  - "3.6-dev"

#install dependences
install:
  - pip install -r requirements.txt

#Run tests
script:
  - pytest --with-coverage --cover-package=app

after_success:
  - coveralls
